apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init
        image: alpine/git
        args:
        - clone
        - git@github.com:jepra777/jere-wp-stateless-repo.git
        - /var/www/html
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
        - name: wordpress-dotssh
          mountPath: /root/.ssh/
          readOnly: true

      containers:
      - name: wordpress
        image: wordpress:6.5.5-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
        envFrom:
        - secretRef:
            name: wordpress-secrets
        - configMapRef:
            name: wordpress-env

      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
          readOnly: true
        - name: nginx
          mountPath: /etc/nginx/conf.d
          readOnly: true

      volumes:
      - name: www-data
        emptyDir: {}
      - name: wordpress-dotssh
        secret:
          secretName: wordpress-dotssh
          defaultMode: 0600
      - name: nginx
        configMap:
          name: wordpress-nginx
