apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-content-uploads
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-replicated
  resources:
    requests:
      storage: 5Gi
