apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        fsGroup: 33

      initContainers:
      - name: init
        image: alpine/git
        command:
        - /bin/sh
        - -c
        args:
        - cd /var/www/html;
          git clone https://github.com/jepra777/jere-wp-stateless-repo.git .;
          git reset --hard $HASH;
          rm -rf .git
        env:
        - name: HASH
          value: origin/main
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
      
      containers:
      - name: wordpress
        image: wordpress:6.7.1-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
        - name: wp-content-uploads
          mountPath: /var/www/html/wp-content/uploads
        envFrom:
        - secretRef:
            name: wordpress-secrets
        - configMapRef:
            name: wordpress-env
 
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
          readOnly: true
        - name: wp-content-uploads
          mountPath: /var/www/html/wp-content/uploads
          readOnly: true
        - name: nginx
          mountPath: /etc/nginx/conf.d
          readOnly: true
 
      volumes:
      - name: www-data
        emptyDir: {}
      - name: nginx
        configMap:
          name: wordpress-nginx
      - name: wp-content-uploads
        persistentVolumeClaim:
          claimName: wp-content-uploads
